### PR TITLE
Added placeholders for homes and home coordinates.

### PR DESCRIPTION
**Pull request by ipsk**
Added the placeholders to get the home's name and coordinates.
This allows to do some pretty nice things like a GUI for homes with a correct TP to the location and their name.

The placeholders are `%essentials_home_<number>%` and `%essentials_home_<number>_<x|y|z>`.

I made it return and empty string instead of null when the home number is higher than the current homes the player has, so it'd be easier to use as instead of sometimes it working it would always return "" if the number is high.

Here is an example of it ingame: https://img.mattmoreira.me/image_8ada0e.png

### CODE REVIEW

**Comment by Sxtanna** [comment]
```java
// Removes all the letters from the identifier to get the home slot.
String homeNumberString = identifier.replaceAll("\\D+", "");
// Checks if the number slot is an integer or not.
if (!isStringInt(homeNumberString)) return null;
// Since it is easier for users to type from 1-x I subtract one from the original number to work from 0-x.
int homeNumber = Integer.parseInt(homeNumberString) - 1;
```

This entire process can be replaced with 

```java
Integer homeNumber = Ints.tryParse(identifier.replaceAll("\\D+", "")) - 1;
```

Because Guava

**Comment by Sxtanna** [comment]
```java
if (identifier.endsWith("_x")) {                                                                              
    try {                                                                                                     
        return String.valueOf(round(essentials.getUser(p).getHome(getHomeName(p, homeNumber)).getX())) + ".5";
    } catch (Exception e) {                                                                                   
        return null;                                                                                          
    }                                                                                                         
}                                                                                                             
if (identifier.endsWith("_y")) {                                                                              
    try {                                                                                                     
        return String.valueOf(round(essentials.getUser(p).getHome(getHomeName(p, homeNumber)).getY())) + ".5";
    } catch (Exception e) {                                                                                   
        return null;                                                                                          
    }                                                                                                         
}                                                                                                             
if (identifier.endsWith("_z")) {                                                                              
    try {                                                                                                     
        return String.valueOf(round(essentials.getUser(p).getHome(getHomeName(p, homeNumber)).getZ())) + ".5";
    } catch (Exception e) {                                                                                   
        return null;                                                                                          
    }                                                                                                         
}                  
```

Theres no real reason for you to not surround this entire block with a single try catch                  

```java
try {                                                                                                         
    if (identifier.endsWith("_x")) {                                                                          
        return String.valueOf(round(essentials.getUser(p).getHome(getHomeName(p, homeNumber)).getX())) + ".5";
    }                                                                                                         
    if (identifier.endsWith("_y")) {                                                                          
        return String.valueOf(round(essentials.getUser(p).getHome(getHomeName(p, homeNumber)).getY())) + ".5";
    }                                                                                                         
    if (identifier.endsWith("_z")) {                                                                          
        return String.valueOf(round(essentials.getUser(p).getHome(getHomeName(p, homeNumber)).getZ())) + ".5";
    }                                                                                                         
}                                                                                                             
catch (Exception e) {                                                                                         
                                                                                                              
}                                                                                                             
```

**Comment by ipsk** [comment]
@Sxtanna Thank you for the changes, didn't think about that!
I'll change them in a bit.
Though when trying to do the `int homeNumber = Ints.tryParse(identifier.replaceAll("\\D+", "")) - 1;` I get `Unboxing of 'Ints.tryParse(identifier.replaceAll("\\D+", ""))' may produce 'java.lang.NullPointerException' ` Should I just ignore that or would be better to add a check on it?

**Comment by Sxtanna** [comment]
@ipsk That makes sense, as Ints.tryParse returns either the int or null if it couldn't be parsed. 

You absolutely should do a null check, however take a loot at my code again. The type should be 
`Integer` 
and not 
`int`.

You should also move that `- 1` to where the home is actually looked up.

**Comment by extendedclip** [comment]
If this looks good to you guys, we can merge. LMK.

**Comment by Sxtanna** [comment]
@extendedclip I would highly recommend some slight changes to make the code comply with the DRY principle a bit more, and remove some of these repeating `String.valueOf` calls.

**Comment by Sxtanna** [comment]
After that, it should be fine

**Comment by pastamilk** [comment]
Any reason this wasn't implemented?

**Comment by ipsk** [comment]
@pastamilk I kinda forgot about it

**Comment by pastamilk** [comment]
Any progress by chance?

**Comment by ipsk** [comment]
Moved to https://github.com/PlaceholderAPI/Essentials-Expansion/pull/23.

**Pull request closed without merging**
