### PR TITLE
Remove .5 appending from Home location

### PR DESCRIPTION
**Pull request by Andre601**
Why was that evene appended to begin with?

Also, if the X one looks weird is it because I accidentally committed directly to master when I wanted to make a PR, so I reverted it (poorly).

### CODE REVIEW

**Comment by VeilStar** [comment]
Presumably the intention was to append .5 to an int and not a double, so that the coordinate is centered on the top face of a block. This PR would at least return a number, but I would assume this is still incorrect, and instead it should be cast to an int and .5 should be appended to that int.

**Comment by Andre601** [comment]
> Presumably the intention was to append .5 to an int and not a double, so that the coordinate is centered on the top face of a block. This PR would at least return a number, but I would assume this is still incorrect, and instead it should be cast to an int and .5 should be appended to that int.

You are aware that an int can't have fractials..... right?

**Comment by VeilStar** [comment]
Yes. I meant as a string.

**Comment by Andre601** [comment]
The issue is still a pointless .5 for the X and Z coordinates for homes, which makes no sense to do.

See #43 for why this is an issue.

**Comment by BlitzOffline** [comment]
If no one has anything to add to this, I'll be merging in the next few days. Andre is right imo. The .5 there is probably from a time when the placeholder was returning an integer instead of the exact coord(double/float) and since most people wanted the center of the block they appended .5. Location#getX returns a double tho so the exact coords of the /sethome is returned now.

**Pull request merged**
