### PR TITLE
Fixed safe_online method.

### PR DESCRIPTION
**Pull request by UnioDex**
Fixes https://github.com/PlaceholderAPI/Essentials-Expansion/issues/11

### CODE REVIEW

**Comment by extendedclip** [comment]
You tested and it now shows the expected output?

**Comment by UnioDex** [comment]
Yes. I'm using it on my production server right now and everything is working.

Btw there is no net.ess3.EssentialsX artifact in your public repo. You might need to add EssentialsX's official repo to pom.xml or add EssentialsX to your repo.

**Comment by extendedclip** [comment]
Ah yeah, I’ll update the repo later today. You have a link to the official one?

**Comment by UnioDex** [comment]
Yeah, here:
https://ci.ender.zone/plugin/repository/everything/

**Comment by extendedclip** [comment]
Thanks for the quick fix btw.

**Comment by UnioDex** [comment]
You're welcome.

**Pull request merged**
